const apiInfo = {
  title: 'Warhammer 40K Learning API',
  version: '1.0.0',
  description: 'Учебный read API с узнаваемыми сущностями Warhammer 40,000 и едиными query-правилами.',
  audience: 'Frontend и fullstack-разработчики.',
  basePath: '/api/v1',
};

const gettingStartedSteps = [
  {
    title: 'Начни с overview',
    description: 'Увидь ресурсы, примеры запросов и форму ответов.',
    endpoint: '/api/v1/overview',
  },
  {
    title: 'Построй первый каталог',
    description: 'Список characters или factions с пагинацией и search.',
    endpoint: '/api/v1/characters?limit=6&sort=-powerLevel,name',
  },
  {
    title: 'Подключи include',
    description: 'Получи faction, race, homeworld и events за один запрос.',
    endpoint: '/api/v1/characters?filter[faction]=ultramarines&include=faction,race,homeworld,events',
  },
  {
    title: 'Попробуй конкурентные запросы',
    description: 'Собери dashboard через Promise.all.',
    endpoint: '/api/v1/examples/concurrency',
  },
];

const featuredQueries = [
  {
    title: 'Сортировка персонажей по влиянию',
    description: 'Простой старт для карточек и страниц деталей.',
    path: '/api/v1/characters?limit=6&sort=-powerLevel,name',
  },
  {
    title: 'События современной эпохи',
    description: 'Подходит для timeline и filter UI.',
    path: '/api/v1/events?filter[era]=indomitus-era&include=planets,factions,characters',
  },
  {
    title: 'Сравнение фракций',
    description: 'Готовый сценарий для compare page и сравнительных карточек.',
    path: '/api/v1/compare/factions?ids=imperium-of-man,black-legion&include=races,leaders,homeworld',
  },
  {
    title: 'Глобальный search',
    description: 'Один input, несколько списков результатов.',
    path: '/api/v1/search?search=cadia&resources=planets,events,factions',
  },
  {
    title: 'Статистика фракций по расам',
    description: 'Подходит для charts, dashboards и учебной агрегации.',
    path: '/api/v1/stats/factions/by-race',
  },
  {
    title: 'Статистика юнитов по фракциям',
    description: 'Готовая сводка для faction dashboard и сравнения ростеров.',
    path: '/api/v1/stats/units/by-faction',
  },
  {
    title: 'Статистика кампаний по организациям',
    description: 'Показывает institutional participation для campaign dashboards и timeline analytics.',
    path: '/api/v1/stats/campaigns/by-organization',
  },
  {
    title: 'Статистика полей битв по фракциям',
    description: 'Тactical analytics для warzone dashboards, filters и compare сценариев.',
    path: '/api/v1/stats/battlefields/by-faction',
  },
  {
    title: 'Статистика систем по segmentum',
    description: 'Sector-level обзор для системной навигации и galactic map UI.',
    path: '/api/v1/stats/star-systems/by-segmentum',
  },
  {
    title: 'Организации внутри Imperium',
    description: 'Подходит для institutional UI, codex browser и сложных relation filters.',
    path: '/api/v1/organizations?filter[faction]=imperium-of-man&include=factions,leaders,homeworld',
  },
  {
    title: 'Звездные системы с мирами',
    description: 'Системный слой для sector maps, route planners и planet navigation UI.',
    path: '/api/v1/star-systems?include=planets,era&sort=name',
  },
  {
    title: 'Случайный персонаж',
    description: 'Быстрая ручка для featured card, hero-блоков и экспериментов.',
    path: '/api/v1/random/character?include=faction,race,homeworld',
  },
  {
    title: 'Юниты с оружием и keywords',
    description: 'Готовый сценарий для карточек армии, tabs и богатых includes.',
    path: '/api/v1/units?filter[faction]=ultramarines&include=factions,weapons,keywords&sort=-powerLevel,name',
  },
  {
    title: 'Сравнение юнитов',
    description: 'Готовый compare endpoint для squad browser, build planner и учебных таблиц.',
    path: '/api/v1/compare/units?ids=terminator-squad,intercessor-squad&include=factions,weapons,keywords',
  },
  {
    title: 'Сравнение организаций',
    description: 'Institutional compare для codex browser, dashboards и political-map UI.',
    path: '/api/v1/compare/organizations?ids=inquisition,adeptus-mechanicus&include=factions,leaders,homeworld,era',
  },
  {
    title: 'Сравнение систем',
    description: 'Полезно для galactic map UI, sector navigation и system-level compare.',
    path: '/api/v1/compare/star-systems?ids=sol-system,macragge-system&include=planets,era',
  },
  {
    title: 'Graph explorer для фракции',
    description: 'Готовый graph endpoint для relation maps, connected detail screen и explorer UI.',
    path: '/api/v1/explore/graph?resource=factions&identifier=imperium-of-man&depth=2&limitPerRelation=4',
  },
  {
    title: 'Graph explorer с whitelist ресурсов',
    description: 'Ограничивает graph только нужными типами ресурсов и упрощает connected UI.',
    path: '/api/v1/explore/graph?resource=factions&identifier=imperium-of-man&depth=2&limitPerRelation=4&resources=campaigns,characters',
  },
  {
    title: 'Path finder от героя к реликвии',
    description: 'Кратчайший путь между двумя сущностями для lore explorer и connected UI.',
    path: '/api/v1/explore/path?fromResource=characters&fromIdentifier=roboute-guilliman&toResource=relics&toIdentifier=emperors-sword&maxDepth=3&limitPerRelation=6&backlinks=true',
  },
  {
    title: 'Поля битв по кампании',
    description: 'Тактический слой для campaign drill-down и graph-heavy docs сценариев.',
    path: '/api/v1/battlefields?filter[campaigns]=plague-wars&include=planet,starSystem,factions,characters,campaigns',
  },
  {
    title: 'Сравнение полей битв',
    description: 'Готовый tactical compare для warzone cards, map overlays и campaign drill-down.',
    path: '/api/v1/compare/battlefields?ids=hesperon-void-line,kasr-partox-ruins&include=planet,starSystem,era,factions,characters,campaigns',
  },
  {
    title: 'Кампании по участникам',
    description: 'Многосторонний ресурс для dashboards, timelines и campaign explorer.',
    path: '/api/v1/campaigns?filter[factions]=imperium-of-man,black-legion&include=planets,characters,organizations',
  },
  {
    title: 'Статистика реликвий по фракциям',
    description: 'Готовая сводка для inventory dashboards и faction identity screens.',
    path: '/api/v1/stats/relics/by-faction',
  },
];

const queryGuide = {
  params: [
    { name: 'page', example: 'page=1', description: 'Номер страницы.' },
    { name: 'limit', example: 'limit=12', description: 'Размер страницы.' },
    { name: 'search', example: 'search=guilliman', description: 'Поиск по текстовым полям с ранжированием по релевантности.' },
    { name: 'sort', example: 'sort=-powerLevel,name', description: 'Сортировка по одному или нескольким полям.' },
    { name: 'filter[...]', example: 'filter[faction]=ultramarines', description: 'Структурированные фильтры.' },
    { name: 'include', example: 'include=faction,race,events', description: 'Связанные сущности в блоке included.' },
    { name: 'fields[...]', example: 'fields[characters]=id,name,slug', description: 'Выборка только нужных полей.' },
    { name: 'resources', example: 'resources=campaigns,characters', description: 'Whitelist типов ресурсов для `search`, `explore/graph` и `explore/path`.' },
  ],
  responseShapes: {
    list: {
      data: [],
      meta: { page: 1, limit: 12, total: 42, totalPages: 4, resource: 'characters' },
      links: { self: '/api/v1/characters?page=1&limit=12', next: '/api/v1/characters?page=2&limit=12' },
      included: { factions: [], races: [] },
    },
    detail: {
      data: {},
      meta: { resource: 'characters' },
      included: {},
    },
    error: {
      error: { code: 'VALIDATION_ERROR', message: 'Invalid query parameters', details: [] },
    },
  },
  scenarios: [
    {
      title: 'Быстрый каталог',
      description: 'Список персонажей, сортировка и пагинация.',
      path: '/api/v1/characters?limit=8&sort=name',
    },
    {
      title: 'Связанные карточки',
      description: 'Детальная страница персонажа со связанными сущностями.',
      path: '/api/v1/characters/roboute-guilliman?include=faction,race,homeworld,events',
    },
    {
      title: 'Сложный фильтр',
      description: 'Отбор событий по эре и участникам.',
      path: '/api/v1/events?filter[era]=indomitus-era&filter[factions]=imperium-of-man,ultramarines',
    },
    {
      title: 'Сравнение двух фракций',
      description: 'Один endpoint для compare page с общими и различающимися атрибутами.',
      path: '/api/v1/compare/factions?ids=imperium-of-man,ultramarines&include=races,leaders,homeworld',
    },
    {
      title: 'Сравнение двух юнитов',
      description: 'Удобный compare endpoint для squad cards, table view и армейских экспериментов.',
      path: '/api/v1/compare/units?ids=terminator-squad,intercessor-squad&include=factions,weapons,keywords',
    },
    {
      title: 'Сравнение двух реликвий',
      description: 'Полезно для hero-item UI, inventory compare и detail screen patterns.',
      path: '/api/v1/compare/relics?ids=emperors-sword,talon-of-horus&include=faction,bearer,originPlanet,keywords',
    },
    {
      title: 'Сравнение двух систем',
      description: 'Показывает, как compare работает и для system-level сущностей без power-метрики.',
      path: '/api/v1/compare/star-systems?ids=sol-system,macragge-system&include=planets,era',
    },
    {
      title: 'Сравнение двух полей битв',
      description: 'Удобно для tactical cards, battlefield browser и campaign drill-down UI.',
      path: '/api/v1/compare/battlefields?ids=hesperon-void-line,kasr-partox-ruins&include=planet,starSystem,era,factions,characters,campaigns',
    },
    {
      title: 'Graph explorer',
      description: 'Один endpoint возвращает nodes и edges для relation-aware detail screen.',
      path: '/api/v1/explore/graph?resource=characters&identifier=roboute-guilliman&depth=2&limitPerRelation=4',
    },
    {
      title: 'Graph explorer с фильтром ресурсов',
      description: 'Оставляет в графе только выбранные типы ресурсов плюс обязательный root.',
      path: '/api/v1/explore/graph?resource=factions&identifier=imperium-of-man&depth=2&limitPerRelation=4&resources=campaigns,characters',
    },
    {
      title: 'Path finder',
      description: 'Возвращает кратчайшую цепочку между двумя сущностями по текущему relation graph.',
      path: '/api/v1/explore/path?fromResource=relics&fromIdentifier=emperors-sword&toResource=campaigns&toIdentifier=plague-wars&maxDepth=4&limitPerRelation=6&backlinks=true',
    },
    {
      title: 'Path finder с whitelist ресурсов',
      description: 'Позволяет ограничить traversal только нужными промежуточными типами ресурсов.',
      path: '/api/v1/explore/path?fromResource=relics&fromIdentifier=emperors-sword&toResource=campaigns&toIdentifier=plague-wars&maxDepth=4&limitPerRelation=6&backlinks=true&resources=factions',
    },
    {
      title: 'Системная карта миров',
      description: 'Показывает star-systems как отдельный уровень навигации над planets.',
      path: '/api/v1/star-systems?include=planets,era&sort=name',
    },
    {
      title: 'Поля битв кампании',
      description: 'Дает tactical drill-down для campaign pages, graph traversal и search-driven exploration.',
      path: '/api/v1/battlefields?filter[campaigns]=plague-wars&include=planet,starSystem,factions,characters,campaigns&sort=-intensityLevel,name',
    },
    {
      title: 'Агрегация для диаграммы',
      description: 'Подготовленные данные для bar chart без ручной агрегации на клиенте.',
      path: '/api/v1/stats/events/by-era',
    },
    {
      title: 'Сводка оружия по keywords',
      description: 'Подходит для charts, legends и exploration UI вокруг weapon profiles.',
      path: '/api/v1/stats/weapons/by-keyword',
    },
    {
      title: 'Кампании по организациям',
      description: 'Агрегация для institutional dashboards и campaign participation charts.',
      path: '/api/v1/stats/campaigns/by-organization',
    },
    {
      title: 'Поля битв по фракциям',
      description: 'Готовый tactical aggregate для warzone charts и faction pressure overlays.',
      path: '/api/v1/stats/battlefields/by-faction',
    },
    {
      title: 'Системы по segmentum',
      description: 'Сводка системного слоя для sector maps и multi-level navigation UI.',
      path: '/api/v1/stats/star-systems/by-segmentum',
    },
    {
      title: 'Реликвии с носителем',
      description: 'Детальные карточки, inventory UI и relation-heavy detail pages.',
      path: '/api/v1/relics?include=faction,bearer,originPlanet,keywords&sort=-powerLevel,name',
    },
  ],
};

const concurrencyExample = {
  title: 'Конкурентная загрузка для dashboard',
  description: 'Несколько endpoint-ов грузятся параллельно, а клиент объединяет результат в один экран.',
  endpoints: [
    '/api/v1/factions?limit=4&sort=name',
    '/api/v1/characters?limit=4&sort=-powerLevel,name',
    '/api/v1/events?limit=4&sort=-yearOrder,name',
  ],
  code: `const [factions, characters, events] = await Promise.all([
  fetch('/api/v1/factions?limit=4&sort=name').then((response) => response.json()),
  fetch('/api/v1/characters?limit=4&sort=-powerLevel,name').then((response) => response.json()),
  fetch('/api/v1/events?limit=4&sort=-yearOrder,name').then((response) => response.json()),
]);`,
};

const dataset = {
  eras: [
    { id: 1, slug: 'great-crusade', name: 'Great Crusade', summary: 'Экспансия Imperium.', description: 'Объединение миров человечества.', status: 'historical', yearLabel: 'M30', yearOrder: 30000, keywords: ['imperium', 'expansion'] },
    { id: 2, slug: 'horus-heresy', name: 'Horus Heresy', summary: 'Гражданская война примархов.', description: 'Крупнейший раскол в истории Imperium.', status: 'historical', yearLabel: 'M31', yearOrder: 31000, keywords: ['civil-war', 'chaos'] },
    { id: 3, slug: 'age-of-imperium', name: 'Age of Imperium', summary: 'Долгий период войны и стагнации.', description: 'Эпоха выживания после Ереси.', status: 'historical', yearLabel: 'M32-M41', yearOrder: 41000, keywords: ['imperium', 'decline'] },
    { id: 4, slug: 'indomitus-era', name: 'Indomitus Era', summary: 'Современный этап после падения Cadia.', description: 'Эра реформ и контрнаступления.', status: 'active', yearLabel: 'M42', yearOrder: 42000, keywords: ['indomitus', 'modern'] },
  ],
  races: [
    { id: 1, slug: 'human', name: 'Human', summary: 'Основной вид Imperium.', description: 'Люди составляют основу множества армий и институтов.', status: 'active', alignment: 'mixed', keywords: ['imperium', 'chaos', 'mankind'] },
    { id: 2, slug: 'aeldari', name: 'Aeldari', summary: 'Древний вид с сильной связью с варпом.', description: 'Немногочисленный, но очень влиятельный вид.', status: 'active', alignment: 'xenos', keywords: ['psychic', 'craftworlds'] },
    { id: 3, slug: 'ork', name: 'Ork', summary: 'Воинственная зелёная биомасса.', description: 'Культура Orks строится вокруг войны.', status: 'active', alignment: 'xenos', keywords: ['waaagh', 'clans'] },
    { id: 4, slug: 'necron', name: 'Necron', summary: 'Бессмертные машинные династии.', description: 'Древние правители возвращаются к войне.', status: 'active', alignment: 'xenos', keywords: ['dynasties', 'ancient'] },
    { id: 5, slug: 'tyranid', name: 'Tyranid', summary: 'Хищный коллективный вид.', description: 'Hive Fleets поглощают целые миры.', status: 'active', alignment: 'xenos', keywords: ['hive-fleets', 'biomass'] },
    { id: 6, slug: 'tau', name: "T'au", summary: 'Молодая технологичная цивилизация.', description: "T'au Empire сочетает экспансию и технологическое превосходство.", status: 'active', alignment: 'xenos', keywords: ['greater-good', 'technology'] },
  ],
  planets: [
    { id: 1, slug: 'terra', name: 'Terra', summary: 'Тронный мир человечества.', description: 'Политическое сердце Imperium.', status: 'active', type: 'throneworld', sector: 'Sol', eraId: 4, starSystemId: 1, keywords: ['imperium', 'throneworld'] },
    { id: 2, slug: 'mars', name: 'Mars', summary: 'Кузница Mechanicus.', description: 'Источник технологий и верфей.', status: 'active', type: 'forge-world', sector: 'Sol', eraId: 4, starSystemId: 1, keywords: ['mechanicus', 'forge'] },
    { id: 3, slug: 'cadia', name: 'Cadia', summary: 'Легендарный мир-крепость.', description: 'Символ стойкости Imperium.', status: 'fallen', type: 'fortress-world', sector: 'Cadian Gate', eraId: 4, starSystemId: 2, keywords: ['imperium', 'fortress'] },
    { id: 4, slug: 'macragge', name: 'Macragge', summary: 'Домашний мир Ultramarines.', description: 'Центр Ultramar и пример дисциплины.', status: 'active', type: 'civilized-world', sector: 'Ultramar', eraId: 4, starSystemId: 3, keywords: ['ultramarines', 'ultramar'] },
    { id: 5, slug: 'armageddon', name: 'Armageddon', summary: 'Индустриальный мир бесконечных войн.', description: 'Хороший пример многостороннего конфликта.', status: 'active', type: 'hive-world', sector: 'Armageddon Sector', eraId: 4, starSystemId: 4, keywords: ['industrial', 'warzone'] },
    { id: 6, slug: 'fenris', name: 'Fenris', summary: 'Суровый ледяной мир.', description: 'Показывает роль homeworld в идентичности фракции.', status: 'active', type: 'death-world', sector: 'Fenris System', eraId: 4, starSystemId: 5, keywords: ['space-wolves', 'death-world'] },
    { id: 7, slug: 'baal', name: 'Baal', summary: 'Родной мир Blood Angels.', description: 'Мир выживания и наследия.', status: 'active', type: 'radiated-world', sector: 'Baal System', eraId: 4, starSystemId: 6, keywords: ['blood-angels', 'imperium'] },
  ],
  starSystems: [
    { id: 1, slug: 'sol-system', name: 'Sol System', summary: 'Сердце Imperium и ядро Segmentum Solar.', description: 'Вмещает Terra, Mars и главный политический узел человечества.', status: 'active', segmentum: 'Segmentum Solar', eraId: 4, keywords: ['imperium', 'core-worlds'] },
    { id: 2, slug: 'cadian-gate-system', name: 'Cadian Gate System', summary: 'Ключевой проход у Великого Разлома.', description: 'Связан с Cadia, обороной прохода и множеством контрнаступлений.', status: 'contested', segmentum: 'Segmentum Obscurus', eraId: 4, keywords: ['cadia', 'gate'] },
    { id: 3, slug: 'macragge-system', name: 'Macragge System', summary: 'Система, задающая ритм Ultramar.', description: 'Удобна для учебных экранов про governance, defense и systems map.', status: 'active', segmentum: 'Ultima Segmentum', eraId: 4, keywords: ['ultramar', 'governance'] },
    { id: 4, slug: 'armageddon-system', name: 'Armageddon System', summary: 'Тяжелая индустриальная система бесконечной войны.', description: 'Подходит для конфликтных dashboards и defense-driven API экспериментов.', status: 'active', segmentum: 'Segmentum Solar', eraId: 4, keywords: ['warzone', 'industrial'] },
    { id: 5, slug: 'fenris-system', name: 'Fenris System', summary: 'Суровая пограничная система Space Wolves.', description: 'Хорошо показывает связь chapter identity и локального окружения.', status: 'active', segmentum: 'Segmentum Obscurus', eraId: 4, keywords: ['space-wolves', 'frontier'] },
    { id: 6, slug: 'baal-system', name: 'Baal System', summary: 'Кроваво-красная система Blood Angels.', description: 'Сильная опора для campaign detail и homeworld-driven navigation.', status: 'scarred', segmentum: 'Ultima Segmentum', eraId: 4, keywords: ['blood-angels', 'defense'] },
  ],
  factions: [
    { id: 1, slug: 'imperium-of-man', name: 'Imperium of Man', summary: 'Гигантская человеческая империя.', description: 'Объединяет бесчисленные миры и армии.', status: 'active', alignment: 'imperium', raceIds: [1], homeworldId: 1, eraId: 4, leaderIds: [1, 2], keywords: ['imperium', 'empire'], powerLevel: 99 },
    { id: 2, slug: 'ultramarines', name: 'Ultramarines', summary: 'Образцовый chapter Space Marines.', description: 'Удобная фракция для базовых frontend-упражнений.', status: 'active', alignment: 'imperium', parentFactionId: 1, raceIds: [1], homeworldId: 4, eraId: 4, leaderIds: [2], keywords: ['space-marines', 'ultramar'], powerLevel: 93 },
    { id: 3, slug: 'black-legion', name: 'Black Legion', summary: 'Крупная ударная сила Chaos.', description: 'Хорошо подходит для compare и событий Fall of Cadia.', status: 'active', alignment: 'chaos', raceIds: [1], eraId: 4, leaderIds: [4], keywords: ['chaos', 'traitor-legion'], powerLevel: 94 },
    { id: 4, slug: 'aeldari', name: 'Aeldari', summary: 'Древняя цивилизация.', description: 'Полезна для тем древности и дальновидности.', status: 'active', alignment: 'xenos', raceIds: [2], eraId: 4, leaderIds: [6], keywords: ['craftworlds', 'psychic'], powerLevel: 88 },
    { id: 5, slug: 'orks', name: 'Orks', summary: 'Масса кланов и постоянная война.', description: 'Яркий xenos-полюс учебного набора.', status: 'active', alignment: 'xenos', raceIds: [3], eraId: 4, leaderIds: [5], homeworldId: 5, keywords: ['waaagh', 'clans'], powerLevel: 90 },
    { id: 6, slug: 'necrons', name: 'Necrons', summary: 'Древние машинные династии.', description: 'Усиливают слой данных про эпохи и мощь.', status: 'active', alignment: 'xenos', raceIds: [4], eraId: 4, leaderIds: [7], keywords: ['dynasties', 'ancient'], powerLevel: 91 },
    { id: 7, slug: 'tau-empire', name: "T'au Empire", summary: 'Технологичная ксенос-держава.', description: 'Пример молодого и рационального игрока.', status: 'active', alignment: 'xenos', raceIds: [6], eraId: 4, leaderIds: [8], keywords: ['greater-good', 'technology'], powerLevel: 82 },
    { id: 8, slug: 'adepta-sororitas', name: 'Adepta Sororitas', summary: 'Воинствующий религиозный орден.', description: 'Фракция с яркой верой и символикой.', status: 'active', alignment: 'imperium', parentFactionId: 1, raceIds: [1], eraId: 4, leaderIds: [9], homeworldId: 1, keywords: ['faith', 'imperium'], powerLevel: 80 },
    { id: 9, slug: 'astra-militarum', name: 'Astra Militarum', summary: 'Массовая армия Imperium.', description: 'Удобна для сценариев про кампании и оборону.', status: 'active', alignment: 'imperium', parentFactionId: 1, raceIds: [1], eraId: 4, leaderIds: [10], homeworldId: 3, keywords: ['guard', 'imperium'], powerLevel: 84 },
    { id: 10, slug: 'blood-angels', name: 'Blood Angels', summary: 'Знаменитый chapter Space Marines.', description: 'Расширяет набор homeworld-ов и событий.', status: 'active', alignment: 'imperium', parentFactionId: 1, raceIds: [1], eraId: 4, leaderIds: [11], homeworldId: 7, keywords: ['space-marines', 'baal'], powerLevel: 89 },
  ],
  keywords: [
    { id: 1, slug: 'infantry', name: 'Infantry', description: 'Пешие подразделения для базовых и массовых боевых ролей.', category: 'battlefield-role' },
    { id: 2, slug: 'elite', name: 'Elite', description: 'Элитные подразделения и оружие с повышенной ценностью.', category: 'battlefield-role' },
    { id: 3, slug: 'ranged', name: 'Ranged', description: 'Акцент на дистанционный бой и огневое давление.', category: 'combat-style' },
    { id: 4, slug: 'melee', name: 'Melee', description: 'Акцент на ближний бой, натиск и захват темпа.', category: 'combat-style' },
    { id: 5, slug: 'psychic', name: 'Psychic', description: 'Связь с варпом, психосилами и аномальными эффектами.', category: 'specialism' },
    { id: 6, slug: 'siege', name: 'Siege', description: 'Осады, подавление укреплений и тяжелое наступление.', category: 'warfare' },
    { id: 7, slug: 'faith', name: 'Faith', description: 'Религиозная доктрина и мотивы святой войны.', category: 'doctrine' },
    { id: 8, slug: 'xenos', name: 'Xenos', description: 'Технологии и доктрины, характерные для нечеловеческих цивилизаций.', category: 'faction-tag' },
    { id: 9, slug: 'rapid-fire', name: 'Rapid Fire', description: 'Высокая плотность стрельбы и быстрый темп огня.', category: 'weapon-profile' },
    { id: 10, slug: 'energy', name: 'Energy', description: 'Энергетическое оружие и высокотехнологичные боевые системы.', category: 'weapon-profile' },
    { id: 11, slug: 'bolt', name: 'Bolt', description: 'Болтерное семейство вооружения Imperium.', category: 'weapon-family' },
    { id: 12, slug: 'gauss', name: 'Gauss', description: 'Гаусс-технологии Necrons и их разборные лучевые эффекты.', category: 'weapon-family' },
    { id: 13, slug: 'flame', name: 'Flame', description: 'Огнеметные профили для зачистки и давления на ближней дистанции.', category: 'weapon-profile' },
    { id: 14, slug: 'heavy', name: 'Heavy', description: 'Тяжелое вооружение и отряды огневой поддержки.', category: 'battlefield-role' },
  ],
  weapons: [
    { id: 1, slug: 'bolt-rifle', name: 'Bolt Rifle', summary: 'Универсальное болтерное оружие Primaris Space Marines.', description: 'Хороший базовый пример средней дальности, давления и bolt-профиля.', status: 'active', weaponType: 'rifle', powerLevel: 72, factionId: 2, eraId: 4, keywordIds: [3, 9, 11] },
    { id: 2, slug: 'storm-bolter', name: 'Storm Bolter', summary: 'Компактное болтерное оружие с высоким темпом огня.', description: 'Подходит для elite units и учебных сценариев с rapid fire.', status: 'active', weaponType: 'storm-bolter', powerLevel: 78, factionId: 1, eraId: 4, keywordIds: [2, 3, 9, 11] },
    { id: 3, slug: 'chainsword', name: 'Chainsword', summary: 'Классическое цепное оружие ближнего боя.', description: 'Простой и узнаваемый melee-профиль для многих отрядов Imperium и Chaos.', status: 'active', weaponType: 'blade', powerLevel: 58, factionId: 1, eraId: 4, keywordIds: [4] },
    { id: 4, slug: 'power-sword', name: 'Power Sword', summary: 'Энергетический клинок для elite боевых ролей.', description: 'Связывает melee, elite и технологическое превосходство.', status: 'active', weaponType: 'power-weapon', powerLevel: 81, factionId: 1, eraId: 4, keywordIds: [2, 4, 10] },
    { id: 5, slug: 'heavy-bolter', name: 'Heavy Bolter', summary: 'Тяжелое bolter-оружие огневой поддержки.', description: 'Подходит для siege и heavy support сценариев.', status: 'active', weaponType: 'heavy-weapon', powerLevel: 84, factionId: 9, eraId: 4, keywordIds: [3, 6, 11, 14] },
    { id: 6, slug: 'gauss-flayer', name: 'Gauss Flayer', summary: 'Базовое гаусс-оружие Necron Warriors.', description: 'Сильный xenos-пример для техно-ориентированных loadout-ов.', status: 'active', weaponType: 'gauss-rifle', powerLevel: 79, factionId: 6, eraId: 4, keywordIds: [3, 8, 10, 12] },
    { id: 7, slug: 'shoota', name: 'Shoota', summary: 'Импровизированное, но опасное стрелковое оружие Orks.', description: 'Яркий пример грубой, но рабочей xenos-инженерии.', status: 'active', weaponType: 'slug-thrower', powerLevel: 63, factionId: 5, eraId: 4, keywordIds: [3, 8] },
    { id: 8, slug: 'pulse-rifle', name: 'Pulse Rifle', summary: "Точное дальнобойное оружие T'au Fire Warriors.", description: 'Подходит для учебных примеров про технологическое дальнобойное превосходство.', status: 'active', weaponType: 'pulse-weapon', powerLevel: 76, factionId: 7, eraId: 4, keywordIds: [3, 8, 10] },
    { id: 9, slug: 'flamer', name: 'Flamer', summary: 'Огнемет для зачистки и давления на ближней дистанции.', description: 'Хороший пример шаблонного оружия для aggressive short-range UI.', status: 'active', weaponType: 'flame-weapon', powerLevel: 68, factionId: 8, eraId: 4, keywordIds: [3, 13] },
    { id: 10, slug: 'force-sword', name: 'Force Sword', summary: 'Психически усиленный клинок.', description: 'Соединяет melee и psychic-подход в одном weapon profile.', status: 'active', weaponType: 'force-weapon', powerLevel: 85, factionId: 1, eraId: 4, keywordIds: [4, 5, 10] },
    { id: 11, slug: 'lasgun', name: 'Lasgun', summary: 'Массовое стандартное оружие Astra Militarum.', description: 'Классический учебный пример дешевого массового ranged loadout.', status: 'active', weaponType: 'laser-rifle', powerLevel: 54, factionId: 9, eraId: 4, keywordIds: [1, 3] },
    { id: 12, slug: 'choppa', name: 'Choppa', summary: 'Грубое рубящее оружие Orks.', description: 'Простой melee-инструмент для агрессивных толповых отрядов.', status: 'active', weaponType: 'axe', powerLevel: 57, factionId: 5, eraId: 4, keywordIds: [4, 8] },
    { id: 13, slug: 'power-fist', name: 'Power Fist', summary: 'Тяжелое силовое оружие для elite assault units.', description: 'Высокая ударная мощь и визуально понятный high-impact profile.', status: 'active', weaponType: 'power-weapon', powerLevel: 88, factionId: 2, eraId: 4, keywordIds: [2, 4, 10, 14] },
  ],
  units: [
    { id: 1, slug: 'intercessor-squad', name: 'Intercessor Squad', summary: 'Линейное подразделение Primaris Space Marines.', description: 'Хорошая базовая unit-карточка для списков армии и detail page.', status: 'active', unitType: 'line-infantry', powerLevel: 85, eraId: 4, factionIds: [2], keywordIds: [1, 3, 9, 11], weaponIds: [1, 3] },
    { id: 2, slug: 'terminator-squad', name: 'Terminator Squad', summary: 'Тяжелобронированная elite infantry.', description: 'Удобный пример дорогого elite-отряда с богатым loadout.', status: 'active', unitType: 'elite-infantry', powerLevel: 92, eraId: 4, factionIds: [2], keywordIds: [1, 2, 3, 4, 14], weaponIds: [2, 13] },
    { id: 3, slug: 'battle-sisters-squad', name: 'Battle Sisters Squad', summary: 'Основной боевой отряд Adepta Sororitas.', description: 'Соединяет line infantry, faith-мотивы и агрессивный short-range pressure.', status: 'active', unitType: 'line-infantry', powerLevel: 80, eraId: 4, factionIds: [8], keywordIds: [1, 3, 7], weaponIds: [2, 9] },
    { id: 4, slug: 'cadian-shock-troops', name: 'Cadian Shock Troops', summary: 'Стандартный строевой отряд Astra Militarum.', description: 'Учебный эталон массовой infantry для больших каталогов и cheap-unit UI.', status: 'active', unitType: 'line-infantry', powerLevel: 74, eraId: 4, factionIds: [9], keywordIds: [1, 3, 6], weaponIds: [11] },
    { id: 5, slug: 'ork-boyz', name: 'Ork Boyz', summary: 'Основная боевая масса Orks.', description: 'Отличный пример толпового unit с простым, но ярким набором атрибутов.', status: 'active', unitType: 'line-infantry', powerLevel: 76, eraId: 4, factionIds: [5], keywordIds: [1, 4, 8], weaponIds: [7, 12] },
    { id: 6, slug: 'necron-warriors', name: 'Necron Warriors', summary: 'Базовые строевые бойцы пробудившихся династий.', description: 'Хорошо подходят для UI со строгими, повторяемыми xenos data patterns.', status: 'active', unitType: 'line-infantry', powerLevel: 81, eraId: 4, factionIds: [6], keywordIds: [1, 3, 8, 10, 12], weaponIds: [6] },
    { id: 7, slug: 'fire-warrior-team', name: 'Fire Warrior Team', summary: "Строевой отряд T'au Empire с упором на огневую мощь.", description: 'Показывает, как технологичная фракция влияет на unit и weapon filters.', status: 'active', unitType: 'line-infantry', powerLevel: 77, eraId: 4, factionIds: [7], keywordIds: [1, 3, 8, 10], weaponIds: [8] },
    { id: 8, slug: 'sanguinary-guard', name: 'Sanguinary Guard', summary: 'Элитная ударная гвардия Blood Angels.', description: 'Подходит для premium-card UI и compare со стандартной infantry.', status: 'active', unitType: 'elite-infantry', powerLevel: 90, eraId: 4, factionIds: [10], keywordIds: [2, 4], weaponIds: [4] },
    { id: 9, slug: 'havoc-squad', name: 'Havoc Squad', summary: 'Тяжелая огневая поддержка Chaos Space Marines.', description: 'Удобный пример heavy support unit для build planner и squad browser.', status: 'active', unitType: 'heavy-support', powerLevel: 86, eraId: 4, factionIds: [3], keywordIds: [1, 3, 6, 14], weaponIds: [5] },
    { id: 10, slug: 'primaris-librarian', name: 'Primaris Librarian', summary: 'Психически одаренный specialist отряд Space Marines.', description: 'Соединяет psychic, melee и elite-паттерны в одном объекте.', status: 'active', unitType: 'specialist', powerLevel: 88, eraId: 4, factionIds: [2], keywordIds: [2, 4, 5], weaponIds: [10] },
  ],
  organizations: [
    { id: 1, slug: 'inquisition', name: 'Inquisition', summary: 'Теневой надзор за угрозами Imperium.', description: 'Сильный institutional resource для relation-heavy screens и filters.', status: 'active', organizationType: 'ordo', influenceLevel: 95, homeworldId: 1, eraId: 4, factionIds: [1, 8], leaderIds: [9], keywords: ['imperium', 'faith'] },
    { id: 2, slug: 'adeptus-mechanicus', name: 'Adeptus Mechanicus', summary: 'Культ Машины и хранители технологий.', description: 'Подходит для связок между Mars, технологиями, relics и campaigns.', status: 'active', organizationType: 'tech-priesthood', influenceLevel: 92, homeworldId: 2, eraId: 4, factionIds: [1], leaderIds: [], keywords: ['mechanicus', 'forge'] },
    { id: 3, slug: 'ecclesiarchy', name: 'Ecclesiarchy', summary: 'Имперская церковь и политическая сила веры.', description: 'Полезна для faith-driven UI и связи между персонажами, relics и campaigns.', status: 'active', organizationType: 'state-church', influenceLevel: 88, homeworldId: 1, eraId: 4, factionIds: [1, 8], leaderIds: [9], keywords: ['faith', 'imperium'] },
    { id: 4, slug: 'deathwatch', name: 'Deathwatch', summary: 'Элитное братство для борьбы с xenos.', description: 'Хорошо подходит для filters по organizations и военных task-force страниц.', status: 'active', organizationType: 'chamber-militant', influenceLevel: 84, homeworldId: 1, eraId: 4, factionIds: [1, 2, 10], leaderIds: [2], keywords: ['elite', 'xenos'] },
    { id: 5, slug: 'triarch', name: 'Triarch', summary: 'Древний правящий контур династий Necrons.', description: 'Добавляет institutional слой для древних держав и campaign analytics.', status: 'active', organizationType: 'dynastic-court', influenceLevel: 86, eraId: 4, factionIds: [6], leaderIds: [7], keywords: ['dynasties', 'ancient'] },
    { id: 6, slug: 'fire-caste-command', name: 'Fire Caste Command', summary: "Военный центр T'au Empire.", description: 'Удобный пример military command структуры для filters и compare организационного уровня.', status: 'active', organizationType: 'military-command', influenceLevel: 79, eraId: 4, factionIds: [7], leaderIds: [8], keywords: ['greater-good', 'technology'] },
  ],
  relics: [
    { id: 1, slug: 'emperors-sword', name: "Emperor's Sword", summary: 'Пламенный клинок, ставший символом возвращения Guilliman.', description: 'Сильный flagship relic для detail pages и power-driven sorting.', status: 'active', relicType: 'master-crafted-weapon', powerLevel: 99, factionId: 1, bearerCharacterId: 2, originPlanetId: 1, eraId: 4, keywordIds: [2, 10] },
    { id: 2, slug: 'armour-of-fate', name: 'Armour of Fate', summary: 'Реликтовый доспех, поддерживающий Primarch в новой эре.', description: 'Хорош для inventory UI и связок между bearer, faction и origin.', status: 'active', relicType: 'armor', powerLevel: 95, factionId: 2, bearerCharacterId: 2, originPlanetId: 4, eraId: 4, keywordIds: [2, 10] },
    { id: 3, slug: 'talon-of-horus', name: 'Talon of Horus', summary: 'Легендарное когтевое оружие Abaddon.', description: 'Связывает Chaos, relic cards и сильные compare-сценарии персонажей.', status: 'active', relicType: 'weapon', powerLevel: 94, factionId: 3, bearerCharacterId: 4, originPlanetId: 1, eraId: 4, keywordIds: [2, 4, 10] },
    { id: 4, slug: 'drachnyen', name: "Drach'nyen", summary: 'Пугающий демонический клинок Abaddon.', description: 'Полезен для high-stakes detail UI и темных веток search.', status: 'active', relicType: 'daemon-weapon', powerLevel: 97, factionId: 3, bearerCharacterId: 4, eraId: 4, keywordIds: [4, 10] },
    { id: 5, slug: 'gauntlets-of-ultramar', name: 'Gauntlets of Ultramar', summary: 'Знаковые реликтовые перчатки Primarch.', description: 'Хороший пример hero relic с четкой faction identity и power sorting.', status: 'active', relicType: 'weapon-system', powerLevel: 92, factionId: 2, bearerCharacterId: 2, originPlanetId: 4, eraId: 4, keywordIds: [2, 10, 14] },
    { id: 6, slug: 'ardent-blade', name: 'Ardent Blade', summary: 'Оружие святой войны Saint Celestine.', description: 'Соединяет faith, bearer detail и faction-tagged relic lists.', status: 'active', relicType: 'sacred-weapon', powerLevel: 88, factionId: 8, bearerCharacterId: 9, originPlanetId: 1, eraId: 4, keywordIds: [7, 10] },
  ],
  events: [
    { id: 1, slug: 'horus-heresy', name: 'Horus Heresy', summary: 'Гражданская война, сломавшая Imperium.', description: 'Ключевой исторический узел для множества связей.', status: 'historical', eraId: 2, yearLabel: 'M31', yearOrder: 31000, planetIds: [1, 2], factionIds: [1, 2, 3], characterIds: [1, 3, 4], keywords: ['civil-war', 'primarchs'] },
    { id: 2, slug: 'battle-of-macragge', name: 'Battle of Macragge', summary: 'Оборона Macragge от Tyranids.', description: 'Эталонный пример оборонительной кампании.', status: 'historical', eraId: 3, yearLabel: '745.M41', yearOrder: 41745, planetIds: [4], factionIds: [2, 10], characterIds: [2, 11], keywords: ['defense', 'tyranids'] },
    { id: 3, slug: 'third-war-for-armageddon', name: 'Third War for Armageddon', summary: 'Большая война за Armageddon.', description: 'Удобная точка для compare Imperium и Orks.', status: 'historical', eraId: 3, yearLabel: '998.M41', yearOrder: 41998, planetIds: [5], factionIds: [5, 9], characterIds: [5, 10], keywords: ['siege', 'waaagh'] },
    { id: 4, slug: 'fall-of-cadia', name: 'Fall of Cadia', summary: 'Разрушение Cadia и слом старого баланса.', description: 'Событие с высокой ценностью для search и filters.', status: 'historical', eraId: 4, yearLabel: '999.M41', yearOrder: 41999, planetIds: [3], factionIds: [1, 3, 9], characterIds: [4, 10], keywords: ['cadia', 'chaos'] },
    { id: 5, slug: 'indomitus-crusade', name: 'Indomitus Crusade', summary: 'Контрнаступление Imperium после возвращения Guilliman.', description: 'Один из лучших modern-era examples.', status: 'active', eraId: 4, yearLabel: 'M42', yearOrder: 42000, planetIds: [1, 3, 4], factionIds: [1, 2, 8, 9, 10], characterIds: [2, 9, 10, 11, 12], keywords: ['indomitus', 'crusade'] },
  ],
  campaigns: [
    { id: 1, slug: 'plague-wars', name: 'Plague Wars', summary: 'Долгая кампания за Ultramar против сил Chaos.', description: 'Многоэтапный campaign resource для screens с timelines, factions и organizations.', status: 'active', campaignType: 'crusade', eraId: 4, yearLabel: 'Early M42', yearOrder: 42001, planetIds: [4], factionIds: [1, 2, 3], characterIds: [2, 4], organizationIds: [1, 2], keywords: ['indomitus', 'siege'] },
    { id: 2, slug: 'armageddon-defense-front', name: 'Armageddon Defense Front', summary: 'Кампания обороны Armageddon против Orks.', description: 'Хороший пример campaign explorer с planet, factions и iconic defenders.', status: 'historical', campaignType: 'defense', eraId: 3, yearLabel: '998.M41', yearOrder: 41998, planetIds: [5], factionIds: [5, 9], characterIds: [5, 10], organizationIds: [1], keywords: ['siege', 'guard'] },
    { id: 3, slug: 'defense-of-baal', name: 'Defense of Baal', summary: 'Оборонительная кампания вокруг Baal.', description: 'Подходит для relation-rich campaign detail pages с chapter identity и faith motifs.', status: 'historical', campaignType: 'defense', eraId: 4, yearLabel: 'Transition to M42', yearOrder: 42000, planetIds: [7], factionIds: [1, 10], characterIds: [2, 11], organizationIds: [3, 4], keywords: ['defense', 'faith'] },
    { id: 4, slug: 'pariah-nexus-containment', name: 'Pariah Nexus Containment', summary: 'Попытки сдержать давление Necron-зон подавления.', description: 'Сильный учебный пример campaign-level данных про древние угрозы и технологические ответы.', status: 'active', campaignType: 'containment', eraId: 4, yearLabel: 'Mid M42', yearOrder: 42003, planetIds: [1, 2], factionIds: [1, 6], characterIds: [2, 7], organizationIds: [1, 2, 5], keywords: ['ancient', 'psychic'] },
    { id: 5, slug: 'cadian-gate-counteroffensive', name: 'Cadian Gate Counteroffensive', summary: 'Серия ответных операций после падения Cadia.', description: 'Полезна для dashboards по multi-faction campaign pressure и recovery efforts.', status: 'active', campaignType: 'counteroffensive', eraId: 4, yearLabel: 'Late M42', yearOrder: 42004, planetIds: [3], factionIds: [1, 3, 9], characterIds: [2, 4, 10], organizationIds: [1, 4], keywords: ['cadia', 'crusade'] },
  ],
  battlefields: [
    { id: 1, slug: 'hesperon-void-line', name: 'Hesperon Void Line', summary: 'Космический рубеж кампании Plague Wars.', description: 'Связывает Macragge System, Ultramar и контратаки против Black Legion.', status: 'active', battlefieldType: 'void-front', terrain: 'orbital-bastions', intensityLevel: 94, planetId: 4, starSystemId: 3, eraId: 4, factionIds: [1, 2, 3], characterIds: [2, 4], campaignIds: [1], keywords: ['void-war', 'siege'] },
    { id: 2, slug: 'hades-hive-bulwark', name: 'Hades Hive Bulwark', summary: 'Главный оборонительный пояс Armageddon.', description: 'Учебный пример battlefield detail для defense campaign, Ork pressure и urban war.', status: 'historical', battlefieldType: 'fortress-line', terrain: 'ash-hive', intensityLevel: 91, planetId: 5, starSystemId: 4, eraId: 3, factionIds: [5, 9], characterIds: [5, 10], campaignIds: [2], keywords: ['hive-war', 'defense'] },
    { id: 3, slug: 'angelic-redoubts', name: 'Angelic Redoubts', summary: 'Оборонительные бастионы вокруг Baal.', description: 'Подходит для path и graph между Blood Angels, campaign и system-level навигацией.', status: 'historical', battlefieldType: 'redoubt-network', terrain: 'radiated-desert', intensityLevel: 96, planetId: 7, starSystemId: 6, eraId: 4, factionIds: [1, 10], characterIds: [2, 11], campaignIds: [3], keywords: ['defense', 'redoubts'] },
    { id: 4, slug: 'null-bastion-corridor', name: 'Null Bastion Corridor', summary: 'Полоса подавления в зоне Pariah Nexus.', description: 'Дает graph-связь между Necrons, containment campaign и star-system scope без обязательного planet detail.', status: 'active', battlefieldType: 'suppression-zone', terrain: 'null-field', intensityLevel: 93, starSystemId: 2, eraId: 4, factionIds: [1, 6], characterIds: [2, 7], campaignIds: [4], keywords: ['null-zone', 'ancient'] },
    { id: 5, slug: 'kasr-partox-ruins', name: 'Kasr Partox Ruins', summary: 'Поле боев после падения Cadia.', description: 'Сильная точка для search, compare и campaign-driven battlefield lists.', status: 'active', battlefieldType: 'ruined-fortress', terrain: 'fortress-ruins', intensityLevel: 92, planetId: 3, starSystemId: 2, eraId: 4, factionIds: [1, 3, 9], characterIds: [4, 10], campaignIds: [5], keywords: ['cadia', 'counteroffensive'] },
    { id: 6, slug: 'eternity-gate-approach', name: 'Eternity Gate Approach', summary: 'Последний рубеж обороны Терры во времена Ереси.', description: 'Исторический battlefield для связки Emperor, Horus Heresy и core-world graph.', status: 'historical', battlefieldType: 'siege-gate', terrain: 'palace-fortress', intensityLevel: 100, planetId: 1, starSystemId: 1, eraId: 2, factionIds: [1, 3], characterIds: [1, 3], campaignIds: [], keywords: ['terra', 'siege'] },
  ],
  characters: [
    { id: 1, slug: 'emperor-of-mankind', name: 'The Emperor of Mankind', summary: 'Создатель Imperium.', description: 'Фундаментальная точка отсчета для множества ресурсов.', status: 'enthroned', factionId: 1, raceId: 1, homeworldId: 1, eraId: 3, eventIds: [1], titles: ['Master of Mankind', 'Lord of the Imperium'], keywords: ['imperium', 'psychic'], alignment: 'imperium', powerLevel: 100 },
    { id: 2, slug: 'roboute-guilliman', name: 'Roboute Guilliman', summary: 'Primarch Ultramarines и лицо современного Imperium.', description: 'Подходит для details page с include и timeline.', status: 'active', factionId: 2, raceId: 1, homeworldId: 4, eraId: 4, eventIds: [2, 5], titles: ['Primarch of the Ultramarines', 'Lord Commander of the Imperium'], keywords: ['primarch', 'ultramar'], alignment: 'imperium', powerLevel: 98 },
    { id: 3, slug: 'horus-lupercal', name: 'Horus Lupercal', summary: 'Военачальник крестового похода, ставший мятежником.', description: 'Ключевая фигура Horus Heresy.', status: 'dead', factionId: 3, raceId: 1, homeworldId: 1, eraId: 2, eventIds: [1], titles: ['Warmaster'], keywords: ['chaos', 'primarch'], alignment: 'chaos', powerLevel: 97 },
    { id: 4, slug: 'abaddon-the-despoiler', name: 'Abaddon the Despoiler', summary: 'Верховный лидер Black Legion.', description: 'Связывает Chaos, Cadia и compare page.', status: 'active', factionId: 3, raceId: 1, eraId: 4, eventIds: [1, 4], titles: ['Warmaster of Chaos'], keywords: ['chaos', 'black-legion'], alignment: 'chaos', powerLevel: 96 },
    { id: 5, slug: 'ghazghkull-thraka', name: 'Ghazghkull Thraka', summary: 'Главный warboss современного WAAAGH!.', description: 'Яркий xenos-лидер для фронтенд-упражнений.', status: 'active', factionId: 5, raceId: 3, homeworldId: 5, eraId: 4, eventIds: [3], titles: ['Prophet of the Waaagh!'], keywords: ['orks', 'waaagh'], alignment: 'xenos', powerLevel: 92 },
    { id: 6, slug: 'eldrad-ulthran', name: 'Eldrad Ulthran', summary: 'Один из самых известных farseer Aeldari.', description: 'Хороший пример древнего и дальновидного персонажа.', status: 'active', factionId: 4, raceId: 2, eraId: 4, eventIds: [], titles: ['Farseer'], keywords: ['aeldari', 'psychic'], alignment: 'xenos', powerLevel: 90 },
    { id: 7, slug: 'imotekh-the-stormlord', name: 'Imotekh the Stormlord', summary: 'Влиятельный лидер Necrons.', description: 'Усиливает слой данных про династии и древнюю власть.', status: 'active', factionId: 6, raceId: 4, eraId: 4, eventIds: [], titles: ['Phaeron of the Sautekh Dynasty'], keywords: ['necrons', 'dynasty'], alignment: 'xenos', powerLevel: 91 },
    { id: 8, slug: 'commander-shadowsun', name: 'Commander Shadowsun', summary: "Легендарный командир T'au Empire.", description: "Соединяет modern command structure и T'au politics.", status: 'active', factionId: 7, raceId: 6, eraId: 4, eventIds: [], titles: ['Supreme Commander'], keywords: ['tau', 'greater-good'], alignment: 'xenos', powerLevel: 85 },
    { id: 9, slug: 'saint-celestine', name: 'Saint Celestine', summary: 'Живая святая Imperium.', description: 'Полезна для сценариев про веру и высокие stakes.', status: 'active', factionId: 8, raceId: 1, homeworldId: 1, eraId: 4, eventIds: [5], titles: ['Living Saint'], keywords: ['faith', 'imperium'], alignment: 'imperium', powerLevel: 87 },
    { id: 10, slug: 'commissar-yarrick', name: 'Commissar Yarrick', summary: 'Герой Astra Militarum и Armageddon.', description: 'Удобен для конкурентных запросов к events и planets.', status: 'legendary', factionId: 9, raceId: 1, homeworldId: 3, eraId: 4, eventIds: [3, 4, 5], titles: ['Hero of Hades Hive'], keywords: ['guard', 'cadia'], alignment: 'imperium', powerLevel: 83 },
    { id: 11, slug: 'dante', name: 'Dante', summary: 'Глава Blood Angels.', description: 'Соединяет chapter, homeworld и крупные события.', status: 'active', factionId: 10, raceId: 1, homeworldId: 7, eraId: 4, eventIds: [2, 5], titles: ['Chapter Master of the Blood Angels'], keywords: ['blood-angels', 'space-marines'], alignment: 'imperium', powerLevel: 88 },
    { id: 12, slug: 'lion-eljonson', name: "Lion El'Jonson", summary: 'Primarch Dark Angels.', description: 'Добавляет второй primarch-полюс современной эпохе.', status: 'active', factionId: 1, raceId: 1, homeworldId: 1, eraId: 4, eventIds: [5], titles: ['Primarch of the Dark Angels'], keywords: ['primarch', 'imperium'], alignment: 'imperium', powerLevel: 95 },
  ],
};

const resourceOrder = ['eras', 'races', 'star-systems', 'planets', 'factions', 'organizations', 'keywords', 'weapons', 'relics', 'units', 'events', 'campaigns', 'battlefields', 'characters'];

const resourceDefinitions = {
  eras: {
    label: 'Эры',
    description: 'Хронологические периоды для timeline и исторических фильтров.',
    defaultSort: 'yearOrder,name',
    previewParams: { limit: 4, sort: 'yearOrder,name' },
    searchFields: ['name', 'summary', 'description', 'keywords'],
    sortFields: ['name', 'status', 'yearOrder'],
    filters: {
      status: { type: 'attribute', field: 'status', label: 'Статус' },
      keywords: { type: 'array', field: 'keywords', label: 'Keywords' },
    },
    includes: {},
    fields: [
      { name: 'id', type: 'number', description: 'Числовой идентификатор.' },
      { name: 'slug', type: 'string', description: 'Публичный slug.' },
      { name: 'name', type: 'string', description: 'Название эры.' },
      { name: 'status', type: 'string', description: 'Активная или историческая.' },
      { name: 'yearOrder', type: 'number', description: 'Поле для сортировки.' },
    ],
    sampleQueries: ['/api/v1/eras?sort=yearOrder', '/api/v1/eras?filter[status]=active'],
  },
  races: {
    label: 'Расы',
    description: 'Базовый слой домена для фильтров и связей.',
    defaultSort: 'name',
    previewParams: { limit: 6, sort: 'name' },
    searchFields: ['name', 'summary', 'description', 'keywords'],
    sortFields: ['name', 'status', 'alignment'],
    filters: {
      status: { type: 'attribute', field: 'status', label: 'Статус' },
      alignment: { type: 'attribute', field: 'alignment', label: 'Alignment' },
      keywords: { type: 'array', field: 'keywords', label: 'Keywords' },
    },
    includes: {},
    fields: [
      { name: 'id', type: 'number', description: 'Числовой идентификатор.' },
      { name: 'slug', type: 'string', description: 'Публичный slug.' },
      { name: 'name', type: 'string', description: 'Название вида.' },
      { name: 'alignment', type: 'string', description: 'Общий полюс роли.' },
    ],
    sampleQueries: ['/api/v1/races?sort=name', '/api/v1/races?filter[alignment]=xenos'],
  },
  'star-systems': {
    label: 'Звездные системы',
    description: 'Слой системного масштаба для maps, graph traversal и навигации между мирами.',
    defaultSort: 'name',
    previewParams: { limit: 6, sort: 'name', include: 'planets,era' },
    searchFields: ['name', 'summary', 'description', 'segmentum', 'keywords'],
    sortFields: ['name', 'status', 'segmentum'],
    filters: {
      status: { type: 'attribute', field: 'status', label: 'Статус' },
      segmentum: { type: 'attribute', field: 'segmentum', label: 'Сегментум' },
      era: { type: 'relation', resource: 'eras', localField: 'eraId', label: 'Эра' },
      planets: { type: 'relation', resource: 'planets', localField: 'planetIds', many: true, label: 'Миры' },
      keywords: { type: 'array', field: 'keywords', label: 'Keywords' },
    },
    includes: {
      planets: { resource: 'planets', localField: 'planetIds', many: true, label: 'Миры' },
      era: { resource: 'eras', localField: 'eraId', label: 'Эра' },
    },
    fields: [
      { name: 'id', type: 'number', description: 'Числовой идентификатор.' },
      { name: 'slug', type: 'string', description: 'Публичный slug.' },
      { name: 'name', type: 'string', description: 'Название системы.' },
      { name: 'segmentum', type: 'string', description: 'Имперский макрорегион.' },
      { name: 'planetIds', type: 'number[]', description: 'Миры, входящие в систему.' },
    ],
    sampleQueries: ['/api/v1/star-systems?include=planets,era&sort=name', '/api/v1/star-systems?filter[planets]=terra,mars'],
  },
  planets: {
    label: 'Миры',
    description: 'Миры для homeworld, осад и кампаний.',
    defaultSort: 'name',
    previewParams: { limit: 6, sort: 'name', include: 'era,starSystem' },
    searchFields: ['name', 'summary', 'description', 'sector', 'keywords'],
    sortFields: ['name', 'status', 'type', 'sector'],
    filters: {
      status: { type: 'attribute', field: 'status', label: 'Статус' },
      type: { type: 'attribute', field: 'type', label: 'Тип мира' },
      era: { type: 'relation', resource: 'eras', localField: 'eraId', label: 'Эра' },
      starSystem: { type: 'relation', resource: 'star-systems', localField: 'starSystemId', label: 'Звездная система' },
      keywords: { type: 'array', field: 'keywords', label: 'Keywords' },
    },
    includes: {
      era: { resource: 'eras', localField: 'eraId', label: 'Эра' },
      starSystem: { resource: 'star-systems', localField: 'starSystemId', label: 'Звездная система' },
    },
    fields: [
      { name: 'id', type: 'number', description: 'Числовой идентификатор.' },
      { name: 'slug', type: 'string', description: 'Публичный slug.' },
      { name: 'name', type: 'string', description: 'Название мира.' },
      { name: 'type', type: 'string', description: 'Категория мира.' },
      { name: 'sector', type: 'string', description: 'Сектор или регион.' },
      { name: 'starSystemId', type: 'number', description: 'Связь с системой.' },
    ],
    sampleQueries: ['/api/v1/planets?include=era,starSystem&sort=name', '/api/v1/planets?filter[starSystem]=sol-system'],
  },
  factions: {
    label: 'Фракции',
    description: 'Ключевой ресурс для быстрых frontend-экспериментов.',
    defaultSort: 'name',
    previewParams: { limit: 6, sort: '-powerLevel,name', include: 'leaders,races,homeworld' },
    searchFields: ['name', 'summary', 'description', 'keywords', 'alignment'],
    sortFields: ['name', 'status', 'alignment', 'powerLevel'],
    filters: {
      alignment: { type: 'attribute', field: 'alignment', label: 'Alignment' },
      status: { type: 'attribute', field: 'status', label: 'Статус' },
      race: { type: 'relation', resource: 'races', localField: 'raceIds', many: true, label: 'Раса' },
      era: { type: 'relation', resource: 'eras', localField: 'eraId', label: 'Эра' },
      keywords: { type: 'array', field: 'keywords', label: 'Keywords' },
    },
    includes: {
      races: { resource: 'races', localField: 'raceIds', many: true, label: 'Расы' },
      leaders: { resource: 'characters', localField: 'leaderIds', many: true, label: 'Лидеры' },
      homeworld: { resource: 'planets', localField: 'homeworldId', label: 'Родной мир' },
      era: { resource: 'eras', localField: 'eraId', label: 'Эра' },
      parentFaction: { resource: 'factions', localField: 'parentFactionId', label: 'Родительская фракция' },
    },
    fields: [
      { name: 'id', type: 'number', description: 'Числовой идентификатор.' },
      { name: 'slug', type: 'string', description: 'Публичный slug.' },
      { name: 'name', type: 'string', description: 'Название фракции.' },
      { name: 'alignment', type: 'string', description: 'Политический полюс.' },
      { name: 'powerLevel', type: 'number', description: 'Условная учебная метрика.' },
    ],
    sampleQueries: ['/api/v1/factions?include=leaders,races,homeworld&sort=-powerLevel,name', '/api/v1/factions?filter[alignment]=imperium'],
  },
  organizations: {
    label: 'Организации',
    description: 'Институции, ордена и командные структуры для более сложных графов связей.',
    defaultSort: '-influenceLevel,name',
    previewParams: { limit: 6, sort: '-influenceLevel,name', include: 'factions,leaders,homeworld' },
    searchFields: ['name', 'summary', 'description', 'organizationType', 'keywords'],
    sortFields: ['name', 'status', 'organizationType', 'influenceLevel'],
    filters: {
      status: { type: 'attribute', field: 'status', label: 'Статус' },
      type: { type: 'attribute', field: 'organizationType', label: 'Тип организации' },
      faction: { type: 'relation', resource: 'factions', localField: 'factionIds', many: true, label: 'Фракция' },
      leader: { type: 'relation', resource: 'characters', localField: 'leaderIds', many: true, label: 'Лидер' },
      homeworld: { type: 'relation', resource: 'planets', localField: 'homeworldId', label: 'Родной мир' },
      era: { type: 'relation', resource: 'eras', localField: 'eraId', label: 'Эра' },
      keywords: { type: 'array', field: 'keywords', label: 'Keywords' },
    },
    includes: {
      factions: { resource: 'factions', localField: 'factionIds', many: true, label: 'Фракции' },
      leaders: { resource: 'characters', localField: 'leaderIds', many: true, label: 'Лидеры' },
      homeworld: { resource: 'planets', localField: 'homeworldId', label: 'Родной мир' },
      era: { resource: 'eras', localField: 'eraId', label: 'Эра' },
    },
    fields: [
      { name: 'id', type: 'number', description: 'Числовой идентификатор.' },
      { name: 'slug', type: 'string', description: 'Публичный slug.' },
      { name: 'name', type: 'string', description: 'Название организации.' },
      { name: 'organizationType', type: 'string', description: 'Вид институции или ордена.' },
      { name: 'influenceLevel', type: 'number', description: 'Условная метрика политического или стратегического веса.' },
      { name: 'factionIds', type: 'number[]', description: 'Связанные фракции.' },
      { name: 'leaderIds', type: 'number[]', description: 'Лидеры или знаковые фигуры.' },
    ],
    sampleQueries: ['/api/v1/organizations?include=factions,leaders,homeworld&sort=-influenceLevel,name', '/api/v1/organizations?filter[faction]=imperium-of-man&filter[type]=ordo'],
  },
  keywords: {
    label: 'Keywords',
    description: 'Нормализованные теги для units и weapons, полезные для chips, filters и legends.',
    defaultSort: 'name',
    previewParams: { limit: 8, sort: 'name' },
    searchFields: ['name', 'description', 'category'],
    sortFields: ['name', 'category'],
    filters: {
      category: { type: 'attribute', field: 'category', label: 'Категория' },
    },
    includes: {},
    fields: [
      { name: 'id', type: 'number', description: 'Числовой идентификатор.' },
      { name: 'slug', type: 'string', description: 'Публичный slug.' },
      { name: 'name', type: 'string', description: 'Отображаемое имя keyword.' },
      { name: 'category', type: 'string', description: 'Категория keyword.' },
    ],
    sampleQueries: ['/api/v1/keywords?sort=name', '/api/v1/keywords?filter[category]=weapon-profile'],
  },
  weapons: {
    label: 'Оружие',
    description: 'Отдельный ресурс для loadout-ов, unit cards, filters по типу вооружения и tech tree UI.',
    defaultSort: '-powerLevel,name',
    previewParams: { limit: 8, sort: '-powerLevel,name', include: 'faction,era,keywords' },
    searchFields: ['name', 'summary', 'description', 'weaponType'],
    sortFields: ['name', 'status', 'weaponType', 'powerLevel'],
    filters: {
      status: { type: 'attribute', field: 'status', label: 'Статус' },
      type: { type: 'attribute', field: 'weaponType', label: 'Тип оружия' },
      faction: { type: 'relation', resource: 'factions', localField: 'factionId', label: 'Фракция' },
      era: { type: 'relation', resource: 'eras', localField: 'eraId', label: 'Эра' },
      keywords: { type: 'relation', resource: 'keywords', localField: 'keywordIds', many: true, label: 'Keywords' },
    },
    includes: {
      faction: { resource: 'factions', localField: 'factionId', label: 'Фракция' },
      era: { resource: 'eras', localField: 'eraId', label: 'Эра' },
      keywords: { resource: 'keywords', localField: 'keywordIds', many: true, label: 'Keywords' },
    },
    fields: [
      { name: 'id', type: 'number', description: 'Числовой идентификатор.' },
      { name: 'slug', type: 'string', description: 'Публичный slug.' },
      { name: 'name', type: 'string', description: 'Название оружия.' },
      { name: 'weaponType', type: 'string', description: 'Категория вооружения.' },
      { name: 'powerLevel', type: 'number', description: 'Условная учебная метрика.' },
      { name: 'factionId', type: 'number', description: 'Связь с основной фракцией.' },
      { name: 'keywordIds', type: 'number[]', description: 'Связь с нормализованными tags.' },
    ],
    sampleQueries: ['/api/v1/weapons?include=faction,keywords&sort=-powerLevel,name', '/api/v1/weapons?filter[keywords]=bolt,rapid-fire'],
  },
  relics: {
    label: 'Реликвии',
    description: 'Артефакты и священные предметы для inventory UI, detail pages и relation-heavy данных.',
    defaultSort: '-powerLevel,name',
    previewParams: { limit: 6, sort: '-powerLevel,name', include: 'faction,bearer,originPlanet,keywords' },
    searchFields: ['name', 'summary', 'description', 'relicType'],
    sortFields: ['name', 'status', 'relicType', 'powerLevel'],
    filters: {
      status: { type: 'attribute', field: 'status', label: 'Статус' },
      type: { type: 'attribute', field: 'relicType', label: 'Тип реликвии' },
      faction: { type: 'relation', resource: 'factions', localField: 'factionId', label: 'Фракция' },
      bearer: { type: 'relation', resource: 'characters', localField: 'bearerCharacterId', label: 'Носитель' },
      originPlanet: { type: 'relation', resource: 'planets', localField: 'originPlanetId', label: 'Мир происхождения' },
      era: { type: 'relation', resource: 'eras', localField: 'eraId', label: 'Эра' },
      keywords: { type: 'relation', resource: 'keywords', localField: 'keywordIds', many: true, label: 'Keywords' },
    },
    includes: {
      faction: { resource: 'factions', localField: 'factionId', label: 'Фракция' },
      bearer: { resource: 'characters', localField: 'bearerCharacterId', label: 'Носитель' },
      originPlanet: { resource: 'planets', localField: 'originPlanetId', label: 'Мир происхождения' },
      era: { resource: 'eras', localField: 'eraId', label: 'Эра' },
      keywords: { resource: 'keywords', localField: 'keywordIds', many: true, label: 'Keywords' },
    },
    fields: [
      { name: 'id', type: 'number', description: 'Числовой идентификатор.' },
      { name: 'slug', type: 'string', description: 'Публичный slug.' },
      { name: 'name', type: 'string', description: 'Название реликвии.' },
      { name: 'relicType', type: 'string', description: 'Тип артефакта.' },
      { name: 'powerLevel', type: 'number', description: 'Условная учебная метрика.' },
      { name: 'bearerCharacterId', type: 'number', description: 'Текущий носитель реликвии.' },
      { name: 'keywordIds', type: 'number[]', description: 'Связанные нормализованные теги.' },
    ],
    sampleQueries: ['/api/v1/relics?include=faction,bearer,originPlanet,keywords&sort=-powerLevel,name', '/api/v1/relics?filter[bearer]=roboute-guilliman'],
  },
  units: {
    label: 'Юниты',
    description: 'Сильный учебный ресурс для army builder, squad browser, compare cards и rich includes.',
    defaultSort: '-powerLevel,name',
    previewParams: { limit: 8, sort: '-powerLevel,name', include: 'factions,weapons,keywords' },
    searchFields: ['name', 'summary', 'description', 'unitType'],
    sortFields: ['name', 'status', 'unitType', 'powerLevel'],
    filters: {
      status: { type: 'attribute', field: 'status', label: 'Статус' },
      type: { type: 'attribute', field: 'unitType', label: 'Тип юнита' },
      faction: { type: 'relation', resource: 'factions', localField: 'factionIds', many: true, label: 'Фракция' },
      era: { type: 'relation', resource: 'eras', localField: 'eraId', label: 'Эра' },
      keywords: { type: 'relation', resource: 'keywords', localField: 'keywordIds', many: true, label: 'Keywords' },
      weapons: { type: 'relation', resource: 'weapons', localField: 'weaponIds', many: true, label: 'Оружие' },
    },
    includes: {
      factions: { resource: 'factions', localField: 'factionIds', many: true, label: 'Фракции' },
      era: { resource: 'eras', localField: 'eraId', label: 'Эра' },
      keywords: { resource: 'keywords', localField: 'keywordIds', many: true, label: 'Keywords' },
      weapons: { resource: 'weapons', localField: 'weaponIds', many: true, label: 'Оружие' },
    },
    fields: [
      { name: 'id', type: 'number', description: 'Числовой идентификатор.' },
      { name: 'slug', type: 'string', description: 'Публичный slug.' },
      { name: 'name', type: 'string', description: 'Название юнита.' },
      { name: 'unitType', type: 'string', description: 'Категория юнита.' },
      { name: 'powerLevel', type: 'number', description: 'Условная учебная метрика.' },
      { name: 'factionIds', type: 'number[]', description: 'Одна или несколько фракций.' },
      { name: 'weaponIds', type: 'number[]', description: 'Типовые loadout-позиции.' },
      { name: 'keywordIds', type: 'number[]', description: 'Нормализованные tags.' },
    ],
    sampleQueries: ['/api/v1/units?include=factions,weapons,keywords&sort=-powerLevel,name', '/api/v1/units?filter[faction]=ultramarines&filter[keywords]=elite'],
  },
  events: {
    label: 'События',
    description: 'Исторические и современные конфликты для timeline и dashboard.',
    defaultSort: '-yearOrder,name',
    previewParams: { limit: 5, sort: '-yearOrder,name', include: 'era,planets,factions,characters' },
    searchFields: ['name', 'summary', 'description', 'keywords', 'yearLabel'],
    sortFields: ['name', 'status', 'yearOrder'],
    filters: {
      status: { type: 'attribute', field: 'status', label: 'Статус' },
      era: { type: 'relation', resource: 'eras', localField: 'eraId', label: 'Эра' },
      factions: { type: 'relation', resource: 'factions', localField: 'factionIds', many: true, label: 'Фракции' },
      planets: { type: 'relation', resource: 'planets', localField: 'planetIds', many: true, label: 'Миры' },
      keywords: { type: 'array', field: 'keywords', label: 'Keywords' },
    },
    includes: {
      era: { resource: 'eras', localField: 'eraId', label: 'Эра' },
      planets: { resource: 'planets', localField: 'planetIds', many: true, label: 'Миры' },
      factions: { resource: 'factions', localField: 'factionIds', many: true, label: 'Фракции' },
      characters: { resource: 'characters', localField: 'characterIds', many: true, label: 'Персонажи' },
    },
    fields: [
      { name: 'id', type: 'number', description: 'Числовой идентификатор.' },
      { name: 'slug', type: 'string', description: 'Публичный slug.' },
      { name: 'name', type: 'string', description: 'Название события.' },
      { name: 'yearOrder', type: 'number', description: 'Поле сортировки.' },
    ],
    sampleQueries: ['/api/v1/events?include=era,planets,factions,characters&sort=-yearOrder,name', '/api/v1/events?filter[era]=indomitus-era'],
  },
  campaigns: {
    label: 'Кампании',
    description: 'Долгие операции и фронты для timeline explorer, dashboards и multi-resource detail pages.',
    defaultSort: '-yearOrder,name',
    previewParams: { limit: 5, sort: '-yearOrder,name', include: 'era,planets,factions,characters,organizations,battlefields' },
    searchFields: ['name', 'summary', 'description', 'campaignType', 'yearLabel', 'keywords'],
    sortFields: ['name', 'status', 'campaignType', 'yearOrder'],
    filters: {
      status: { type: 'attribute', field: 'status', label: 'Статус' },
      type: { type: 'attribute', field: 'campaignType', label: 'Тип кампании' },
      era: { type: 'relation', resource: 'eras', localField: 'eraId', label: 'Эра' },
      planets: { type: 'relation', resource: 'planets', localField: 'planetIds', many: true, label: 'Миры' },
      factions: { type: 'relation', resource: 'factions', localField: 'factionIds', many: true, label: 'Фракции' },
      characters: { type: 'relation', resource: 'characters', localField: 'characterIds', many: true, label: 'Персонажи' },
      organizations: { type: 'relation', resource: 'organizations', localField: 'organizationIds', many: true, label: 'Организации' },
      battlefields: { type: 'relation', resource: 'battlefields', localField: 'battlefieldIds', many: true, label: 'Поля битв' },
      keywords: { type: 'array', field: 'keywords', label: 'Keywords' },
    },
    includes: {
      era: { resource: 'eras', localField: 'eraId', label: 'Эра' },
      planets: { resource: 'planets', localField: 'planetIds', many: true, label: 'Миры' },
      factions: { resource: 'factions', localField: 'factionIds', many: true, label: 'Фракции' },
      characters: { resource: 'characters', localField: 'characterIds', many: true, label: 'Персонажи' },
      organizations: { resource: 'organizations', localField: 'organizationIds', many: true, label: 'Организации' },
      battlefields: { resource: 'battlefields', localField: 'battlefieldIds', many: true, label: 'Поля битв' },
    },
    fields: [
      { name: 'id', type: 'number', description: 'Числовой идентификатор.' },
      { name: 'slug', type: 'string', description: 'Публичный slug.' },
      { name: 'name', type: 'string', description: 'Название кампании.' },
      { name: 'campaignType', type: 'string', description: 'Категория операции.' },
      { name: 'yearOrder', type: 'number', description: 'Поле сортировки timeline.' },
      { name: 'planetIds', type: 'number[]', description: 'Миры, задействованные в кампании.' },
      { name: 'organizationIds', type: 'number[]', description: 'Организации-участники.' },
      { name: 'battlefieldIds', type: 'number[]', description: 'Связанные поля битв.' },
    ],
    sampleQueries: ['/api/v1/campaigns?include=era,planets,factions,characters,organizations,battlefields&sort=-yearOrder,name', '/api/v1/campaigns?filter[battlefields]=hesperon-void-line'],
  },
  battlefields: {
    label: 'Поля битв',
    description: 'Тактический слой для warzone maps, campaign drill-down и relation-heavy battlefield detail pages.',
    defaultSort: '-intensityLevel,name',
    previewParams: { limit: 6, sort: '-intensityLevel,name', include: 'planet,starSystem,era,factions,characters,campaigns' },
    searchFields: ['name', 'summary', 'description', 'battlefieldType', 'terrain', 'keywords'],
    sortFields: ['name', 'status', 'battlefieldType', 'terrain', 'intensityLevel'],
    filters: {
      status: { type: 'attribute', field: 'status', label: 'Статус' },
      type: { type: 'attribute', field: 'battlefieldType', label: 'Тип поля битвы' },
      terrain: { type: 'attribute', field: 'terrain', label: 'Местность' },
      era: { type: 'relation', resource: 'eras', localField: 'eraId', label: 'Эра' },
      planet: { type: 'relation', resource: 'planets', localField: 'planetId', label: 'Мир' },
      starSystem: { type: 'relation', resource: 'star-systems', localField: 'starSystemId', label: 'Звездная система' },
      factions: { type: 'relation', resource: 'factions', localField: 'factionIds', many: true, label: 'Фракции' },
      characters: { type: 'relation', resource: 'characters', localField: 'characterIds', many: true, label: 'Персонажи' },
      campaigns: { type: 'relation', resource: 'campaigns', localField: 'campaignIds', many: true, label: 'Кампании' },
      keywords: { type: 'array', field: 'keywords', label: 'Keywords' },
    },
    includes: {
      planet: { resource: 'planets', localField: 'planetId', label: 'Мир' },
      starSystem: { resource: 'star-systems', localField: 'starSystemId', label: 'Звездная система' },
      era: { resource: 'eras', localField: 'eraId', label: 'Эра' },
      factions: { resource: 'factions', localField: 'factionIds', many: true, label: 'Фракции' },
      characters: { resource: 'characters', localField: 'characterIds', many: true, label: 'Персонажи' },
      campaigns: { resource: 'campaigns', localField: 'campaignIds', many: true, label: 'Кампании' },
    },
    fields: [
      { name: 'id', type: 'number', description: 'Числовой идентификатор.' },
      { name: 'slug', type: 'string', description: 'Публичный slug.' },
      { name: 'name', type: 'string', description: 'Название поля битвы.' },
      { name: 'battlefieldType', type: 'string', description: 'Категория боевой зоны.' },
      { name: 'terrain', type: 'string', description: 'Тип местности.' },
      { name: 'intensityLevel', type: 'number', description: 'Условная метрика давления и масштаба.' },
      { name: 'campaignIds', type: 'number[]', description: 'Кампании, проходящие через это поле битвы.' },
    ],
    sampleQueries: ['/api/v1/battlefields?include=planet,starSystem,era,factions,characters,campaigns&sort=-intensityLevel,name', '/api/v1/battlefields?filter[campaigns]=plague-wars,cadian-gate-counteroffensive'],
  },
  characters: {
    label: 'Персонажи',
    description: 'Самый удобный ресурс для карточек, search, filters и detail page.',
    defaultSort: '-powerLevel,name',
    previewParams: { limit: 6, sort: '-powerLevel,name', include: 'faction,race,homeworld,events' },
    searchFields: ['name', 'summary', 'description', 'titles', 'keywords', 'alignment'],
    sortFields: ['name', 'status', 'alignment', 'powerLevel'],
    filters: {
      faction: { type: 'relation', resource: 'factions', localField: 'factionId', label: 'Фракция' },
      race: { type: 'relation', resource: 'races', localField: 'raceId', label: 'Раса' },
      era: { type: 'relation', resource: 'eras', localField: 'eraId', label: 'Эра' },
      homeworld: { type: 'relation', resource: 'planets', localField: 'homeworldId', label: 'Родной мир' },
      keywords: { type: 'array', field: 'keywords', label: 'Keywords' },
      alignment: { type: 'attribute', field: 'alignment', label: 'Alignment' },
      status: { type: 'attribute', field: 'status', label: 'Статус' },
    },
    includes: {
      faction: { resource: 'factions', localField: 'factionId', label: 'Фракция' },
      race: { resource: 'races', localField: 'raceId', label: 'Раса' },
      homeworld: { resource: 'planets', localField: 'homeworldId', label: 'Родной мир' },
      era: { resource: 'eras', localField: 'eraId', label: 'Эра' },
      events: { resource: 'events', localField: 'eventIds', many: true, label: 'События' },
    },
    fields: [
      { name: 'id', type: 'number', description: 'Числовой идентификатор.' },
      { name: 'slug', type: 'string', description: 'Публичный slug.' },
      { name: 'name', type: 'string', description: 'Имя персонажа.' },
      { name: 'status', type: 'string', description: 'Состояние персонажа.' },
      { name: 'powerLevel', type: 'number', description: 'Условная учебная метрика.' },
    ],
    sampleQueries: ['/api/v1/characters?filter[faction]=ultramarines&include=faction,race,homeworld,events', '/api/v1/characters?search=primarch&sort=-powerLevel,name'],
  },
};

module.exports = {
  apiInfo,
  concurrencyExample,
  dataset,
  featuredQueries,
  gettingStartedSteps,
  queryGuide,
  resourceDefinitions,
  resourceOrder,
};
